# Generated by Django 4.2.20 on 2025-05-08 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pretixbase', '0279_discount_event_date_from_discount_event_date_until'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='marketing_email_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='order',
            name='marketing_email_consent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer',
            name='locale',
            field=models.CharField(default='en', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='locale',
            field=models.CharField(default='en', max_length=50),
        ),
    ]
